# Generated by Django 3.2.4 on 2021-07-06 08:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('u_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('uFName', models.CharField(max_length=50)),
                ('uLName', models.CharField(max_length=50)),
                ('uRole', models.CharField(max_length=40)),
                ('uEmail', models.EmailField(max_length=100)),
                ('uAvailableHr', models.IntegerField(default=8)),
                ('uPassword', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('t_id', models.AutoField(primary_key=True, serialize=False)),
                ('tName', models.CharField(max_length=100)),
                ('tDescp', models.TextField(max_length=500)),
                ('tPriority', models.IntegerField()),
                ('tExpHr', models.IntegerField()),
                ('u_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EmployeeApp.user')),
            ],
        ),
        migrations.CreateModel(
            name='Assign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('t_status', models.CharField(default='ToDo', max_length=100)),
                ('assignDate', models.DateField()),
                ('assignerName', models.CharField(max_length=100)),
                ('assigneeId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EmployeeApp.user')),
                ('t_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EmployeeApp.task')),
            ],
        ),
    ]
